name : Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code to server
        uses: actions/checkout@v3

      - name: Use Node in server
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
      - run: npm test